# Generated by Django 5.2.17 on 2026-10-01 19:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_minimum', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração da loja',
                'verbose_name_plural': 'configurações da loja',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_storesettings_is_singleton'), models.CheckConstraint(condition=models.Q(('free_shipping_minimum__gt', 0)), name='core_storesettings_free_shipping_minimum_positive')],
            },
        ),
    ]
