# Generated by Django 5.2.17 on 2026-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraccesscode'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', models.F('subtotal'))), name='orders_order_total_matches_subtotal'),
        ),
    ]
