# Generated by Django 5.2.17 on 2026-10-01 22:48

import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraccesscode'),
        ('orders', '0003_order_customer_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='orders_order_total_matches_subtotal',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Cartão'), ('pix', 'Pix')], default='card', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_saved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_last_four',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('pix_discount__gte', 0), ('product_discount__gte', 0), ('shipping_fee__gte', 0), ('shipping_saved__gte', 0)), name='orders_order_adjustments_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('pix_discount')), '+', models.F('shipping_fee')))), name='orders_order_total_matches_breakdown'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_last_four__regex', '^\\d{4}$'), ('payment_method', 'card')), models.Q(('payment_last_four', ''), ('payment_method', 'pix')), _connector='OR'), name='orders_order_payment_reference_matches_method'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method', 'pix'), ('pix_discount', 0), _connector='OR'), name='orders_order_pix_discount_only_for_pix'),
        ),
    ]
