# Generated by Django 5.2.17 on 2026-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=120)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_stock', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(blank=True, max_length=80)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('images', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'external_id'),
                'indexes': [models.Index(fields=['category', 'brand'], name='catalog_category_brand_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_price__gte', 0)), name='catalog_imported_product_price_gte_0'), models.CheckConstraint(condition=models.Q(('source_discount_percentage__isnull', True), models.Q(('source_discount_percentage__gte', 0), ('source_discount_percentage__lte', 100)), _connector='OR'), name='catalog_imported_product_discount_range')],
            },
        ),
    ]
