# Generated by Django 5.2.17 on 2026-09-30 15:56

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('image_url', models.URLField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=500, validators=[apps.catalog.models.validate_link_url])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='catalog_banner_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.importedproduct')),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MenuListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_links', to='catalog.listing')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='catalog.menu')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='menus', through='catalog.MenuListing', to='catalog.listing'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='catalog_listing_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_price__isnull', True), models.Q(('promotional_price__gt', 0), ('promotional_price__lt', models.F('price'))), _connector='OR'), name='catalog_listing_promo_valid'),
        ),
        migrations.AddIndex(
            model_name='menulisting',
            index=models.Index(fields=['menu', 'display_order'], name='catalog_menu_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='menulisting',
            constraint=models.UniqueConstraint(fields=('menu', 'listing'), name='catalog_unique_menu_listing'),
        ),
    ]
